### ISSUE TITLE
How can i use this?

### ISSUE THREAD

**Issue by mort3za** [seveibar/text-pastry#18]
Just typed `1 to 10` and pressed `ctrl+u` but nothing happend. (even with selection)
Also changed key binding to `ctrl-alt-;` and tried again, but again nothing happend.
How this works?

**Comment by harryi3t** [comment]
-  Select multiple cursors either using `alt-shift-arrow`, individual `ctrl-click` or same word select `ctrl-d`
- Once you have the multiple cursors ready, use the command palette and search for `text pastry:....` use either of `1 to x`, `0 to x` or `custom range`

You dont need to type any numbers. That's the whole point of this plugin

**Comment by mort3za** [comment]
Worked very nice, but custom range throws an error.

Uncaught TypeError: atom.workspace.append is not a function
/home/morteza/.atom/packages/text-pastry/lib/text-pastry-view.coffee:60
